//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace m2ostnextservice
{
    using System;
    using System.Collections.Generic;
    
    public partial class masti_parent_teacher_mapping
    {
        public int id_parent_teacher { get; set; }
        public Nullable<int> id_parent { get; set; }
        public Nullable<int> id_teacher { get; set; }
        public Nullable<int> id_parent_org { get; set; }
        public Nullable<int> id_teacher_org { get; set; }
        public string status { get; set; }
    }
}
