//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace m2ostnextservice
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_banner
    {
        public tbl_banner()
        {
            this.tbl_content_banner = new HashSet<tbl_content_banner>();
        }
    
        public int id_banner { get; set; }
        public int id_organization { get; set; }
        public string banner_name { get; set; }
        public string banner_image { get; set; }
        public string banner_action_url { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> updated_date_time { get; set; }
    
        public virtual ICollection<tbl_content_banner> tbl_content_banner { get; set; }
        public virtual tbl_organization tbl_organization { get; set; }
    }
}
