//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace m2ostnextservice
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_assessment_sheet
    {
        public tbl_assessment_sheet()
        {
            this.tbl_assessment_general = new HashSet<tbl_assessment_general>();
        }
    
        public int id_assessment_sheet { get; set; }
        public Nullable<int> id_organization { get; set; }
        public int id_assesment { get; set; }
        public Nullable<int> id_assessment_theme { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> updated_date_time { get; set; }
    
        public virtual tbl_assessment tbl_assessment { get; set; }
        public virtual ICollection<tbl_assessment_general> tbl_assessment_general { get; set; }
        public virtual tbl_organization tbl_organization { get; set; }
    }
}
