//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace m2ostnextservice
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_organization1
    {
        public tbl_organization1()
        {
            this.tbl_assessment = new HashSet<tbl_assessment>();
            this.tbl_assessment_general = new HashSet<tbl_assessment_general1>();
            this.tbl_assessment_sheet = new HashSet<tbl_assessment_sheet1>();
            this.tbl_banner = new HashSet<tbl_banner1>();
            this.tbl_category = new HashSet<tbl_category1>();
            this.tbl_category_order = new HashSet<tbl_category_order1>();
            this.tbl_category_tiles = new HashSet<tbl_category_tiles1>();
            this.tbl_cms_roles = new HashSet<tbl_cms_roles1>();
            this.tbl_content_organization_mapping = new HashSet<tbl_content_organization_mapping1>();
            this.tbl_content_right_association = new HashSet<tbl_content_right_association1>();
            this.tbl_csst_role = new HashSet<tbl_csst_role1>();
            this.tbl_organisation_banner = new HashSet<tbl_organisation_banner1>();
            this.tbl_role = new HashSet<tbl_role2>();
        }
    
        public int ID_ORGANIZATION { get; set; }
        public int ID_INDUSTRY { get; set; }
        public int ID_BUSINESS_TYPE { get; set; }
        public string ORGANIZATION_NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public string LOGO { get; set; }
        public string CONTACT_NAME { get; set; }
        public string CONTACTNUMBER { get; set; }
        public string CONTACTEMAIL { get; set; }
        public string STATUS { get; set; }
        public System.DateTime UPDATED_DATE_TIME { get; set; }
    
        public virtual ICollection<tbl_assessment> tbl_assessment { get; set; }
        public virtual ICollection<tbl_assessment_general1> tbl_assessment_general { get; set; }
        public virtual ICollection<tbl_assessment_sheet1> tbl_assessment_sheet { get; set; }
        public virtual ICollection<tbl_banner1> tbl_banner { get; set; }
        public virtual tbl_business_type1 tbl_business_type { get; set; }
        public virtual ICollection<tbl_category1> tbl_category { get; set; }
        public virtual ICollection<tbl_category_order1> tbl_category_order { get; set; }
        public virtual ICollection<tbl_category_tiles1> tbl_category_tiles { get; set; }
        public virtual ICollection<tbl_cms_roles1> tbl_cms_roles { get; set; }
        public virtual ICollection<tbl_content_organization_mapping1> tbl_content_organization_mapping { get; set; }
        public virtual ICollection<tbl_content_right_association1> tbl_content_right_association { get; set; }
        public virtual ICollection<tbl_csst_role1> tbl_csst_role { get; set; }
        public virtual tbl_industry1 tbl_industry { get; set; }
        public virtual ICollection<tbl_organisation_banner1> tbl_organisation_banner { get; set; }
        public virtual ICollection<tbl_role2> tbl_role { get; set; }
    }
}
