//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace m2ostnextservice
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_content_header
    {
        public tbl_content_header()
        {
            this.tbl_content_header_footer = new HashSet<tbl_content_header_footer>();
        }
    
        public int id_content_header { get; set; }
        public int id_organization { get; set; }
        public string content_header_name { get; set; }
        public string content_header_image { get; set; }
        public string content_header_action_url { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> updated_date_time { get; set; }
    
        public virtual ICollection<tbl_content_header_footer> tbl_content_header_footer { get; set; }
    }
}
